<a href="https://colab.research.google.com/github/Hani-3/Hani-assignments/blob/main/AA_numpy_part_1_hindi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
ar = np.array(l)

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2] ,[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
b = np.matrix(l)

In [9]:
b

matrix([[1, 2, 3, 4]])

In [10]:
a = np.array(l)

In [11]:
a

array([1, 2, 3, 4])

In [12]:
c = a

In [13]:
c

array([1, 2, 3, 4])

In [14]:
a

array([1, 2, 3, 4])

In [15]:
c[0] = 100

In [16]:
c

array([100,   2,   3,   4])

In [17]:
a

array([100,   2,   3,   4])

In [18]:
d = np.copy(a)

In [19]:
d

array([100,   2,   3,   4])

In [20]:
a

array([100,   2,   3,   4])

In [21]:
a[1] = 400

In [22]:
a

array([100, 400,   3,   4])

In [23]:
d

array([100,   2,   3,   4])

In [24]:
#Numpy - Data Types.

In [25]:
l = [2,3,4,5,6]

In [26]:
ar = np.array(l)

In [27]:
ar

array([2, 3, 4, 5, 6])

In [28]:
ar.ndim

1

In [29]:
ar2 = np.array([[1,2,3,4] , [2,3,4,5]])

In [30]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [31]:
ar2.ndim

2

In [32]:
ar.size

5

In [33]:
ar2.size

8

In [34]:
ar

array([2, 3, 4, 5, 6])

In [35]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [36]:
ar.shape

(5,)

In [37]:
ar2.shape

(2, 4)

In [38]:
ar.dtype

dtype('int64')

In [39]:
ar2.dtype

dtype('int64')

In [40]:
ar22 = np.array([(1.4,45,45) , (23,45,66)])

In [41]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [42]:
ar22.dtype

dtype('float64')

In [43]:
list(range(5))

[0, 1, 2, 3, 4]

In [44]:
list(range(0.1 ,5))

TypeError: 'float' object cannot be interpreted as an integer

In [45]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [46]:
list(np.arange(2.3,5.6,.3))

[np.float64(2.3),
 np.float64(2.5999999999999996),
 np.float64(2.8999999999999995),
 np.float64(3.1999999999999993),
 np.float64(3.499999999999999),
 np.float64(3.799999999999999),
 np.float64(4.099999999999999),
 np.float64(4.399999999999999),
 np.float64(4.699999999999998),
 np.float64(4.999999999999998),
 np.float64(5.299999999999998)]

In [47]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [48]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [51]:
ar4 = np.zeros((3,4,2,3))

In [52]:
ar4.ndim

4

In [53]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [54]:
np.ones(4)

array([1., 1., 1., 1.])

In [56]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
on = np.ones((2,3,2))

In [59]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [61]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [62]:
on *4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [63]:
arr = np.random.randn(3,4)

In [71]:
arr

array([[-0.46845054,  0.62027365, -0.51207164, -0.69375073],
       [-0.11324338, -1.36547574,  0.00619278, -0.30559784],
       [ 0.89356192,  0.94735355, -0.30974555,  0.88699283]])

In [64]:
import pandas as pd

In [65]:
pd.DataFrame(arr)

          0         1         2         3
0 -0.468451  0.620274 -0.512072 -0.693751
1 -0.113243 -1.365476  0.006193 -0.305598
2  0.893562  0.947354 -0.309746  0.886993

In [66]:
np.random.rand(3,4)

array([[0.95837874, 0.21677783, 0.38850068, 0.64279673],
       [0.41787086, 0.80853425, 0.92088629, 0.30771989],
       [0.68763348, 0.19764662, 0.97622238, 0.95096088]])

In [70]:
pd.DataFrame(np.random.randint(1,110 , (300,400)))

,0,1,2,3,4,5,6,7,8,9,...,390,391,392,393,394,395,396,397,398,399
0,90,81,109,33,74,39,6,64,68,85,...,7,7,39,38,5,87,49,104,63,90
1,1,47,13,29,13,7,57,83,80,45,...,75,74,93,26,7,32,22,6,46,46
2,2,21,84,37,99,38,20,93,63,82,...,8,105,69,102,54,88,105,55,57,38
3,74,89,9,36,105,51,93,21,23,9,...,17,47,22,20,79,10,77,20,39,77
4,27,22,9,14,44,37,29,43,8,97,...,103,65,58,14,48,19,26,51,76,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,82,86,102,16,39,85,51,69,109,40,...,30,87,57,32,1,40,48,2,48,4
296,1,57,89,14,86,51,103,59,39,75,...,81,56,26,13,80,50,15,41,20,3
297,21,27,26,7,54,44,57,105,24,103,...,107,85,17,11,62,4,72,46,96,90
298,35,79,78,75,4,30,67,78,19,18,...,43,45,40,53,17,19,95,14,2,25
299,57,8,46,20,22,7,74,46,93,58,...,107,97,68,17,101,101,82,2,39,85

In [72]:
arr

array([[-0.46845054,  0.62027365, -0.51207164, -0.69375073],
       [-0.11324338, -1.36547574,  0.00619278, -0.30559784],
       [ 0.89356192,  0.94735355, -0.30974555,  0.88699283]])

In [74]:
arr[1][1]

np.float64(-1.3654757382015454)

In [75]:
arr = np.random.randint(1,100 , (5,5))

In [76]:
arr

array([[97, 29, 51,  3, 80],
       [19, 35, 18, 46, 97],
       [37, 98, 41, 35, 31],
       [37, 27, 35, 15, 70],
       [55, 84, 57, 28, 87]])

In [77]:
arr[arr>50]

array([97, 51, 80, 97, 98, 70, 55, 84, 57, 87])

In [96]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [97]:
arr1

array([[5, 4, 4, 6],
       [7, 8, 6, 6],
       [7, 9, 2, 4]])

In [98]:
arr2

array([[9, 4, 6, 6],
       [1, 1, 9, 7],
       [5, 1, 6, 9]])

In [99]:
arr1+arr2

array([[14,  8, 10, 12],
       [ 8,  9, 15, 13],
       [12, 10,  8, 13]])

In [100]:
arr1-arr2

array([[-4,  0, -2,  0],
       [ 6,  7, -3, -1],
       [ 2,  8, -4, -5]])

In [101]:
arr1/arr2

array([[0.55555556, 1.        , 0.66666667, 1.        ],
       [7.        , 8.        , 0.66666667, 0.85714286],
       [1.4       , 9.        , 0.33333333, 0.44444444]])

In [102]:
arr1 * arr2

array([[45, 16, 24, 36],
       [ 7,  8, 54, 42],
       [35,  9, 12, 36]])

In [103]:
arr1/0

/tmp/ipykernel_2416/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0

array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [104]:
arr1 +100

array([[105, 104, 104, 106],
       [107, 108, 106, 106],
       [107, 109, 102, 104]])

In [105]:
arr1**2

array([[25, 16, 16, 36],
       [49, 64, 36, 36],
       [49, 81,  4, 16]])

In [106]:
np.sqrt(arr1)

array([[2.23606798, 2.        , 2.        , 2.44948974],
       [2.64575131, 2.82842712, 2.44948974, 2.44948974],
       [2.64575131, 3.        , 1.41421356, 2.        ]])

In [107]:
np.exp(arr1)

array([[1.48413159e+02, 5.45981500e+01, 5.45981500e+01, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 4.03428793e+02, 4.03428793e+02],
       [1.09663316e+03, 8.10308393e+03, 7.38905610e+00, 5.45981500e+01]])

In [108]:
np.log10(arr1)

array([[0.69897   , 0.60205999, 0.60205999, 0.77815125],
       [0.84509804, 0.90308999, 0.77815125, 0.77815125],
       [0.84509804, 0.95424251, 0.30103   , 0.60205999]])

In [109]:
arr1>arr2

array([[False, False, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False]])

In [110]:
np.sin(arr1)

array([[-0.95892427, -0.7568025 , -0.7568025 , -0.2794155 ],
       [ 0.6569866 ,  0.98935825, -0.2794155 , -0.2794155 ],
       [ 0.6569866 ,  0.41211849,  0.90929743, -0.7568025 ]])

In [111]:
np.cos(arr1)

array([[ 0.28366219, -0.65364362, -0.65364362,  0.96017029],
       [ 0.75390225, -0.14550003,  0.96017029,  0.96017029],
       [ 0.75390225, -0.91113026, -0.41614684, -0.65364362]])

In [112]:
np.tan(arr1)

array([[-3.38051501,  1.15782128,  1.15782128, -0.29100619],
       [ 0.87144798, -6.79971146, -0.29100619, -0.29100619],
       [ 0.87144798, -0.45231566, -2.18503986,  1.15782128]])

In [113]:
np.mean(arr1)

np.float64(5.666666666666667)

In [114]:
np.median(arr1)

np.float64(6.0)